language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install cmake libgtest-dev valgrind
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
script: make re && cd ./tests && make re && export LD_LIBRARY_PATH=`pwd`/../ && valgrind --leak-check=full --error-exitcode=1 ./launch_tests
